SET NOCOUNT ON
CREATE TABLE #guids (c1 uniqueidentifier DEFAULT NEWID() ROWGUIDCOL)

INSERT #guids DEFAULT VALUES
INSERT #guids DEFAULT VALUES
INSERT #guids DEFAULT VALUES
INSERT #guids DEFAULT VALUES

SELECT ROWGUIDCOL FROM #guids
GO
DROP TABLE #guids
