SET NOCOUNT ON
CREATE TABLE #guids (c1 uniqueidentifier DEFAULT NEWID())

INSERT #guids DEFAULT VALUES
INSERT #guids DEFAULT VALUES
INSERT #guids DEFAULT VALUES
INSERT #guids DEFAULT VALUES

SELECT * FROM #guids
GO
DROP TABLE #guids
