SELECT CUSTOMERS.CustomerNumber, ORDERS.Amount, ITEMS.Description
FROM CUSTOMERS LEFT OUTER JOIN ORDERS ON (CUSTOMERS.CustomerNumber=ORDERS.CustomerNumber)
LEFT OUTER JOIN ITEMS ON (ORDERS.ItemNumber=ITEMS.ItemNumber)
