SELECT 
DATEPART(yy,OrderDate) AS 'Year',
COUNT(CASE DATEPART(qq,OrderDate) WHEN 1 THEN 1 ELSE NULL END) AS Q1,
COUNT(CASE DATEPART(qq,OrderDate) WHEN 2 THEN 1 ELSE NULL END) AS Q2,
COUNT(CASE DATEPART(qq,OrderDate) WHEN 3 THEN 1 ELSE NULL END) AS Q3,
COUNT(CASE DATEPART(qq,OrderDate) WHEN 4 THEN 1 ELSE NULL END) AS Q4,
COUNT(*) AS TotalNumberOfSales
FROM Orders
GROUP BY DATEPART(yy,OrderDate)
ORDER BY 1
