SET NOCOUNT ON
CREATE TABLE #set1 (k1 int identity)

INSERT #set1 DEFAULT VALUES 
INSERT #set1 DEFAULT VALUES 
INSERT #set1 DEFAULT VALUES 
INSERT #set1 DEFAULT VALUES 
INSERT #set1 DEFAULT VALUES 
INSERT #set1 DEFAULT VALUES 
INSERT #set1 DEFAULT VALUES 
INSERT #set1 DEFAULT VALUES 
INSERT #set1 DEFAULT VALUES 
INSERT #set1 DEFAULT VALUES 

SELECT s1.k1 
FROM #set1 s1 JOIN #set1 s2 ON (s1.k1 >= s2.k1)
GROUP BY s1.k1
HAVING (COUNT(*) % 2) = 1

GO
DROP TABLE #set1

